displayName: Governance Owner Agent
schemaName: copilots_gov_owner_01
accessControlPolicy: GroupMembership
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  settings:
    GenerativeActionsEnabled: true

  isAgentConnectable: true
  publishOnImport: true
  isLightweightBot: false
  recognizer:
    kind: GenerativeAIRecognizer

publishedOn: 2026-07-26T14:59:50.0000000Z