displayName: Governor M365
schemaName: copilots_header_04c70
accessControlPolicy: GroupMembership
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  channels:
    - channelId: MsTeams

    - channelId: Microsoft365Copilot

  settings:
    GenerativeActionsEnabled: true

  isAgentConnectable: true
  publishOnImport: true
  gPTSettings:
    defaultSchemaName: copilots_header_04c70.gpt.default

  isLightweightBot: false
  aISettings:
    useModelKnowledge: true
    isFileAnalysisEnabled: false
    isSemanticSearchEnabled: true
    contentModeration: High
    optInUseLatestModels: false

  recognizer:
    kind: GenerativeAIRecognizer

publishedOn: 2026-07-25T22:38:14.0000000Z